on:
  push:
    branches:
      - main
    paths:
      - Cargo.lock

jobs:
  cache:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
