name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4.1.7
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cache"
      - name: Setup mold linker
        uses: rui314/setup-mold@v1
      - name: Build
        run: cargo build --workspace --all-features --all-targets
      - name: Run tests
        run: cargo test --workspace --all-features --all-targets --no-fail-fast
